export const defaultTheme = {
  blackColor: '#333333',
  whiteColor: '#ffffff',
  bgForAbout: '#d8ecfe',
  lightGeenBgColor: '#e1edce',
  darkGreenColor: '#88aa4d',
  lightRedBgColor: '#f8ddd7',
  darkRedBgColor: '#f75531',
  bgForButton: '#fc9b27',
  bgForButtonHover: 'fc7427',
  pagePadding: '90px',
  fontFamily: '"Inter", "Arial", sans-serif',
  titleLineHeight: '115%',
  titleFontWeight: 'bold',
  fontSizeDefault: "18px",
  pageWidth: '1280px',
  indent: "20px",
};